[project]
name = "physiofit_manager"
version = "1.1.0"
description = "Manage PhysioFit input files"
readme = "README.md"
authors = [
    { name = "Loïc Le Grégam", email = "legregam@insa-toulouse.fr" },
]
requires-python = ">=3.8"
dependencies = [
    "pandas (>=1.5.0)",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/MetaboHUB-MetaToul-FluxoMet/PhysioFit_Data_Manager"
"Bug Tracker" = "https://github.com/MetaboHUB-MetaToul-FluxoMet/PhysioFit_Data_Manager/issues"

[project.scripts]
physiofit_manager = "physiofit_manager.cli:main"

[dependency-groups]
dev = [
    "pytest",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
